steps:
  # Init
  - name: hashicorp/terraform:latest
    args: ["-chdir=env/${_ENV}", "init"]

  # Validate
  - name: hashicorp/terraform:latest
    args: ["-chdir=env/${_ENV}", "validate"]

  # Plan
  - name: hashicorp/terraform:latest
    args: ["-chdir=env/${_ENV}", "plan", "-out=tfplan"]

  # Apply
  - name: hashicorp/terraform:latest
    args: ["-chdir=env/${_ENV}", "apply", "-auto-approve", "tfplan"]

substitutions:
  _ENV: dev   # default